### ISSUE TITLE
Payment failed

### ISSUE THREAD

**Issue by slickit** [PaystackHQ/Prestashop-Paystack#4]
Hello,

Site shows 'Your payment for the order failed' after a successful payment. It seems that the plugin is not handling successful transactions properly.
What could be the issue.

Best regards,

**Comment by Kendysond** [comment]
Hello @slickit 

Deep apologies for the tardy response to this issue, I've not had time to work on this in a while. 

Considering the payment was successful, you got the error because the plugin was unable to verify the transaction. Here are two reasons why that could happen: 

1. The secret key you used was incorrect. 
2. Your server was unable to make a CURL request to Paystack's server to verify the transaction. 

If you're sure it's not the first, please send an email to support@paystack.com, they'll be happy to help you debug the issue with your CURL requests.

**Comment by seyi-adetunji** [comment]
Hi Steve,
                    I have already installed the plugin but after payment,
there is redirection error, Can you advise with this?

**Comment by steveamaza** [comment]
Please open an issue on the respective plugin and provide as much information as possible so we can understand what the problem is

**Comment by ikeogu** [comment]
Paystack Request failed with response: 

400 Bad Request
cloudflare
' PLEASE WHATCOULD BE THE PROBLEM I AM TESTING IT USING TEST KEYS

**Comment by steveamaza** [comment]
@ikeogu please open a separate issue for this providing as much information as possible about your site including the link
